apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicon
  labels:
    name: multicon
spec:
  replicas: 3
  selector:
    matchLabels:
      name: multicon
  template:
    metadata:
      labels:
        name: multicon
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: composer
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
        - name: alpine
          image: alpine:3
          volumeMounts:
            - name: shared-data
              mountPath: /pod-data
            - name: config-volume
              mountPath: /etc/config
          command:
            - /bin/sh
            - -c
            - while true; do echo "$(date) My favorite composer:" \
              "$(cat /etc/config/given_name) $(cat /etc/config/surname)" \
              > /pod-data/index.html;
              sleep 10; done;
