# =========================
# 1. ConfigMap (non-sensitive settings)
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "production"
  API_URL: "https://api.example.com"

---
# =========================
# 2. Secret (sensitive data)
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: "student"
  DB_PASS: "secret123"

---
# =========================
# 3. Deployment using both
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo
        image: busybox
        command: ["sh", "-c", "echo 'App started.'; sleep 3600"]
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        volumeMounts:
          - name: secret-files
            mountPath: /etc/creds
            readOnly: true
      volumes:
        - name: secret-files
          secret:
            secretName: app-secret
